SHOW DATABASES;

CREATE DATABASE VIT;
DROP DATABASE VIT;

USE VIT;

CREATE TABLE CSE (
    s_id INT,
    s_name VARCHAR(30),
    s_mark INT
);

DROP TABLE CSE;
SHOW TABLES FROM VIT;

SELECT * FROM CSE;

INSERT INTO CSE VALUES (1001, 'Shivam', 99);
INSERT INTO CSE VALUES (1002, 'Yuvansh', 100);
INSERT INTO CSE VALUES (1003, 'Vivek', 95);
INSERT INTO CSE VALUES (1004, 'Sanjay', 98);
INSERT INTO CSE VALUES (1005, 'Yash', 94);

ALTER TABLE CSE ADD (
    s_contact INT
);

DESC CSE;

ALTER TABLE CSE DROP COLUMN s_contact;

ALTER TABLE CSE ADD (
    s_country VARCHAR(50) DEFAULT 'India'
);

INSERT INTO CSE VALUES (1006, 'Yuvansh Raj Saxena', 69, 'India');
